name = "temp-latency"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "latency_logs"
database_id = "192da489-2477-43b4-a871-08c0644fe816"

[[durable_objects.bindings]]
name = "LATENCY_MESH"
class_name = "LatencyMesh"
script_name = "temp-latency"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LatencyMesh"]
